# -*- coding: utf-8 -*-
"""earth quick.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YZ-ADx_IC1ljeh5WfQX3M79NHHlZ17f6
"""

import pandas as pd
import numpy as np
import pickle
import os

from scipy.sparse import hstack, csr_matrix

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.impute import SimpleImputer
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics import classification_report, accuracy_score, confusion_matrix

# 6 Different Models Imports
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import (
    RandomForestClassifier,
    ExtraTreesClassifier,
    GradientBoostingClassifier,
    HistGradientBoostingClassifier
)
from xgboost import XGBClassifier

import matplotlib.pyplot as plt
import seaborn as sns

# =========================================================
# 1. LOAD ALL 3 DATASETS (RE-EVALUATED STRATEGY)
# =========================================================
print("=" * 60)
print("LOADING & PARSING ALL 3 DATASETS")
print("=" * 60)

# Alag-alag datasets load karna
df2 = pd.read_csv("earthquake_data.csv")
df3 = pd.read_csv("earthquake_1995-2023.csv")

# Combine datasets safely
df = pd.concat([df1, df2, df3], ignore_index=True)
print(f"Total Rows initially loaded: {len(df)}")

# Alert target missing values ko pehle drop karenge taaki clear target mile
df = df.dropna(subset=["alert"]).reset_index(drop=True)

# Soft Deduplication: Sirf exact duplicate coordinates aur target ko drop karenge
# Taaki structural rows safe rahein aur matrix scale up ho ske
df = df.drop_duplicates(subset=["latitude", "longitude", "magnitude", "date_time", "alert"])
df = df.reset_index(drop=True)
print(f"Rows retained after optimized deduplication: {len(df)}")

# Target Variable Encoding
label_encoder = LabelEncoder()
df["alert_encoded"] = label_encoder.fit_transform(df["alert"])

print("\nOptimized Class Distribution:")
print(df["alert"].value_counts())

# =========================================================
# 2. DATE & TIME PATTERNS
# =========================================================
df["date_time"] = pd.to_datetime(df["date_time"], errors="coerce", dayfirst=True)
df["year"] = df["date_time"].dt.year.fillna(df["date_time"].dt.year.median())
df["month"] = df["date_time"].dt.month.fillna(1)
df["day"] = df["date_time"].dt.day.fillna(1)
df["weekday"] = df["date_time"].dt.weekday.fillna(0)

# =========================================================
# 3. CATEGORICAL ENCODING
# =========================================================
categorical_cols = ["magType", "continent", "country"]
encoders = {}

for col in categorical_cols:
    df[col] = df[col].astype(str).fillna("Unknown")
    le = LabelEncoder()
    df[col] = le.fit_transform(df[col])
    encoders[col] = le

# =========================================================
# 4. NUMERIC PROCESSING & IMPUTATION
# =========================================================
num_cols = ["magnitude", "cdi", "mmi", "tsunami", "sig", "nst", "dmin", "gap", "depth", "latitude", "longitude"]
imputer = SimpleImputer(strategy="median")
df[num_cols] = imputer.fit_transform(df[num_cols])

# =========================================================
# 5. ADVANCED GEOGRAPHIC & PHYSICAL FEATURE ENGINEERING
# =========================================================
df["mag_depth_ratio"] = df["magnitude"] / (df["depth"] + 1.0)
df["mag_squared"] = df["magnitude"] ** 2
df["depth_log"] = np.log1p(df["depth"])
df["sig_log"] = np.log1p(df["sig"])
df["mag_sig"] = df["magnitude"] * df["sig"]
df["mmi_cdi_diff"] = np.abs(df["mmi"] - df["cdi"])
df["sig_per_mag"] = df["sig"] / (df["magnitude"] + 0.1)
df["abs_lat"] = df["latitude"].abs()
df["lat_lon_interaction"] = df["latitude"] * df["longitude"]

extra_cols = [
    "mag_depth_ratio", "mag_squared", "depth_log", "sig_log",
    "mag_sig", "mmi_cdi_diff", "sig_per_mag", "abs_lat",
    "lat_lon_interaction", "year", "month", "day", "weekday",
    "magType", "continent", "country"
]

all_features = num_cols + extra_cols
X_num = df[all_features]

# Scale structural coordinates
scaler = StandardScaler()
X_num_scaled = scaler.fit_transform(X_num)

# =========================================================
# 6. TEXT VECTORIZATION (NLP UPDATED)
# =========================================================
# String patterns fallback handle karna
df["text"] = df["title"].astype(str).fillna("") + " " + df["location"].astype(str).fillna("")

# Expanded features size from 800 to 1200 for capturing precise geographic names like Mardan, Sibi etc.
tfidf = TfidfVectorizer(max_features=1200, stop_words="english", ngram_range=(1, 3), min_df=2)
X_text = tfidf.fit_transform(df["text"])

# Combine numeric scales and dense matrix tokens
X = hstack([csr_matrix(X_num_scaled), X_text]).tocsr()
y = df["alert_encoded"].values

# Split data into Train/Test matrix (80-20 Split with Stratification)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, random_state=42, stratify=y)

# Dynamic Target weights allocation for handling gradient systems
classes, counts = np.unique(y_train, return_counts=True)
weights = len(y_train) / (len(classes) * counts)
class_weights_dict = dict(zip(classes, weights))
sample_weights = np.array([class_weights_dict[cls] for cls in y_train])

# =========================================================
# 7. CONFIGURE 6 MODELS (TUNED PARAMS FOR SMALL DATA HANDLING)
# =========================================================
models = {
    "Logistic Regression": LogisticRegression(max_iter=3000, class_weight='balanced', solver='lbfgs', random_state=42),

    "Random Forest": RandomForestClassifier(n_estimators=400, max_depth=12, class_weight='balanced', random_state=42, n_jobs=-1),

    "Extra Trees": ExtraTreesClassifier(n_estimators=400, max_depth=12, class_weight='balanced', random_state=42, n_jobs=-1),

    "Gradient Boosting": GradientBoostingClassifier(n_estimators=250, learning_rate=0.04, max_depth=4, random_state=42),

    "Hist Gradient Boosting": HistGradientBoostingClassifier(max_iter=200, learning_rate=0.04, max_depth=6, random_state=42),

    "XGBoost": XGBClassifier(n_estimators=500, max_depth=5, learning_rate=0.03, subsample=0.8, colsample_bytree=0.8,
                             objective="multi:softprob", eval_metric="mlogloss", random_state=42, n_jobs=-1)
}

# =========================================================
# 8. BENCHMARK LOOPS RUNNING
# =========================================================
print("\n" + "=" * 60)
print("COMPARING AND EVALUATING ALL 6 MODERN MODELS")
print("=" * 60)

model_perf = {}

for name, model in models.items():
    print(f"Running iteration for: {name}...")

    # Check framework constraints for sample weight handling
    if name in ["Gradient Boosting"]:
        model.fit(X_train.toarray(), y_train, sample_weight=sample_weights)
    elif name in ["Hist Gradient Boosting"]:
        model.fit(X_train.toarray(), y_train)
    elif name in ["XGBoost"]:
        model.fit(X_train, y_train, sample_weight=sample_weights)
    else:
        model.fit(X_train, y_train)

    # Evaluate predictions
    if name in ["Gradient Boosting", "Hist Gradient Boosting"]:
        y_pred = model.predict(X_test.toarray())
    else:
        y_pred = model.predict(X_test)

    acc = accuracy_score(y_test, y_pred)
    model_perf[name] = {"accuracy": acc, "model_object": model, "predictions": y_pred}
    print(f"-> {name} Current Accuracy Score: {acc:.4f}\n")

# =========================================================
# 9. AUTO-FETCH THE LOGICAL WINNER
# =========================================================
best_model_name = max(model_perf, key=lambda k: model_perf[k]["accuracy"])
best_model_data = model_perf[best_model_name]

print("\n" + "=" * 60)
print(f"AUTOMATICALLY FETCHED THE BEST MODEL: {best_model_name}")
print("=" * 60)
print(f"Highest Generalization Accuracy: {best_model_data['accuracy']:.4f}")

print(f"\nClassification Metrics Sheet for {best_model_name}:")
print(classification_report(y_test, best_model_data["predictions"], target_names=label_encoder.classes_))

# =========================================================
# 10. GENERATE EXPORT METRIC DIAGRAMS
# =========================================================
cm = confusion_matrix(y_test, best_model_data["predictions"])
plt.figure(figsize=(8, 6))
sns.heatmap(cm, annot=True, fmt="d", cmap="magma",
            xticklabels=label_encoder.classes_, yticklabels=label_encoder.classes_)
plt.title(f"Confusion Matrix Optimization - {best_model_name}")
plt.xlabel("Predicted Label Class")
plt.ylabel("Actual Label Class")
plt.tight_layout()
plt.savefig("best_model_confusion_matrix.png")
plt.close()

# =========================================================
# 11. SERIALIZE WINNER OBJECT TO DISK
# =========================================================
pickle.dump(best_model_data["model_object"], open("earthquake_model.pkl", "wb"))
pickle.dump(scaler, open("scaler.pkl", "wb"))
pickle.dump(imputer, open("imputer.pkl", "wb"))
pickle.dump(tfidf, open("tfidf.pkl", "wb"))
pickle.dump(label_encoder, open("label_encoder.pkl", "wb"))
pickle.dump(encoders, open("categorical_encoders.pkl", "wb"))

print("\n[COMPLETE] Successfully optimized performance pipeline!")
print(f"The best configuration ('{best_model_name}') is packaged into 'earthquake_model.pkl'")

